In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

# Be careful with variables of container data type

In [2]:
# Define NumPy array x1
x = np.array([5, 7, 9])

# Assign x to y
# In this time, instance remains common
y = x

# Confirm results
print(x)
print(y)

[5 7 9]
[5 7 9]


In [3]:
# problem!

# Now, change the value of a particular element of x
x[1] = -1

# Then, the y's value is also changed automatically.
print(x)
print(y)

[ 5 -1  9]
[ 5 -1  9]


In [4]:
# if you don't want to chenge y's value, use copy function
x = np.array([5, 7, 9])
y = x.copy()

# The y's value isn't changed by the change of x's value
x[1] = -1
print(x)
print(y)

[ 5 -1  9]
[5 7 9]


In [5]:
import torch

# x1: all values of shape=[5] are tensor of 1
x1 = torch.ones(5)

# Confirm result
print(x1)

# x2: Numpy generated from x1
x2 = x1.data.numpy()

# Confirm result
print(x2)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [6]:
# Problem!

# Change the value of x1
x1[1] = -1

# The value of x2 is automaically changed
print(x1)
print(x2)

tensor([ 1., -1.,  1.,  1.,  1.])
[ 1. -1.  1.  1.  1.]


In [7]:
# How to change safely

# x1: tensor
x1 = torch.ones(5)

# x2: Numpy copied from x1
x2 = x1.data.numpy().copy()

x1[1] = -1

# Confirm results
print(x1)
print(x2)

tensor([ 1., -1.,  1.,  1.,  1.])
[1. 1. 1. 1. 1.]


# Composite function and how to implement it by Python