# 2. Introduction of PyTorch

In [1]:
# Import required libraries
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import japanize_matplotlib
from IPython.display import display

In [2]:
# Set default font size
plt.rcParams['font.size'] = 14

# Set default graph size
plt.rcParams['figure.figsize'] = (6,6)

# Show grid
plt.rcParams['axes.grid'] = True

## 2.2 Tensor

### Import library

In [3]:
# Pytorch library
import torch

### Create tensors of various ranks

In [4]:
# Rank 0 tensor (scalar)
# Don't be forget to convert from dtype to float32. Numpy convert dtype to float64, and some Libraries doesn't work it. 
r0 = torch.tensor(1.0).float()

# Show type
print(type(r0))

# Show dtype
print(r0.dtype)

<class 'torch.Tensor'>
torch.float32


In [5]:
# Show shape
print(r0.shape)

# Show data
print(r0.data)

torch.Size([])
tensor(1.)


In [7]:
# Rank 1 tensor (vector)

# Create rank 1 NumPy variable
r1_np = np.array([1, 2, 3, 4, 5])
print(r1_np.shape)

# Convert from NumPy to tensor
r1 = torch.tensor(r1_np).float()

# Show dtype
print(r1.dtype)

# Show shape
print(r1.shape)

# Show data
print(r1.data)

(5,)
torch.float32
torch.Size([5])
tensor([1., 2., 3., 4., 5.])


In [8]:
# Rank 2 tensor (matrix)

# Create rank 2 Numpy variable
r2_np = np.array([[1, 5, 6], [4, 3, 2]])
print(r2_np.shape)

# Convert from NumPy to tensor
r2 = torch.tensor(r2_np).float()

# Show shape
print(r2.shape)

# Show data
print(r2.data)

(2, 3)
torch.Size([2, 3])
tensor([[1., 5., 6.],
        [4., 3., 2.]])


In [9]:
# Rank 3 tensor

# Initialize a random seed
torch.manual_seed(123)

# Create a normal distributed variable tensor with shape=[3, 2, 2]
# Function randn sets normal distributeed random numbers (average:0, variance:1) to elements
r3 = torch.randn((3, 2, 2))

# Show shape
print(r3.shape)

# Show data
print(r3.data)

torch.Size([3, 2, 2])
tensor([[[-0.1115,  0.1204],
         [-0.3696, -0.2404]],

        [[-1.1969,  0.2093],
         [-0.9724, -0.7550]],

        [[ 0.3239, -0.1085],
         [ 0.2103, -0.3908]]])


In [10]:
# Rank 4 tensor

# Create tensor with shape=[2, 3, 2, 2] and all elements of it are 1
# function ones sets 1.0 to all elements
r4 = torch.ones((2, 3, 2, 2))

# Show shape
print(r4.shape)

# Show data
print(r4.data)

torch.Size([2, 3, 2, 2])
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])


### Create tensor of integer

In [12]:
# r1 is a rank 1 tensor that has float32 data
# This tensor is converted torch.int64 by long function 
r5 = r1.long()

# Show dtype
print(r5.dtype)

# Show value
print(r5)

torch.int64
tensor([1, 2, 3, 4, 5])


### view function

In [13]:
# How to convert other rank like reshape of NumPy
# Convert to rank 2 from rank 3 
# Set -1 to only an element, then it will be automatically tuned.
r6 = r3.view(3, -1)

# Show shape
# In this case, the number of r3 elements is 12 ([3, 2, 2]:3*2*2=12)
# And the number of r6 elements will be tuned to match 12, so r6.shape will be [3, 4]([3, x]:3*x=12)
print(r6.shape)

# Show data
print(r6.data)

torch.Size([3, 4])
tensor([[-0.1115,  0.1204, -0.3696, -0.2404],
        [-1.1969,  0.2093, -0.9724, -0.7550],
        [ 0.3239, -0.1085,  0.2103, -0.3908]])


In [14]:
# How to convert other rank like reshape of NumPy
# Convert to rank 1 from rank 3 
# Set -1 to only an element, then it will be automatically tuned.
r7 = r3.view(-1)

# Show shape
# In this case, the number of r3 elements is 12 ([3, 2, 2]:3*2*2=12)
# And the number of r6 elements will be tuned to match 12, so r7.shape will be [12]([12]:x=12)
print(r7.shape)

# Show data
print(r7.data)

torch.Size([12])
tensor([-0.1115,  0.1204, -0.3696, -0.2404, -1.1969,  0.2093, -0.9724, -0.7550,
         0.3239, -0.1085,  0.2103, -0.3908])


### Other attriburtes


In [15]:
# Requires_grad
print('requires_grad: ', r1.requires_grad)

# device
print('device: ', r1.device)

requires_grad:  False
device:  cpu


### item function

In [16]:
# item function can get value of class with scaler tensor (rank 0)

item = r0.item()

print(type(item))
print(item)

<class 'float'>
1.0


In [17]:
# Be careful with item function. It can only use rank 0 tensor.

print(r1.item())

RuntimeError: a Tensor with 5 elements cannot be converted to Scalar

In [19]:
# When the number of elements is only one, it's OK to use rank more than 1 tensor.
# example: shape is [1], or [1, 1]
t1 = torch.ones(1)

# show shape
print(t1.shape)

# call item function
print(t1.item())

torch.Size([1])
1.0


### max function

In [21]:
# Show original tensor r2 (shape is [2, 3])
print(r2)

# Call max function without argument, and it will be able to get maximum value of all elements
print(r2.max())

tensor([[1., 5., 6.],
        [4., 3., 2.]])
tensor(6.)
