# 2. Introduction of PyTorch

In [1]:
# Import required libraries
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import japanize_matplotlib
from IPython.display import display

In [2]:
# Set default font size
plt.rcParams['font.size'] = 14

# Set default graph size
plt.rcParams['figure.figsize'] = (6,6)

# Show grid
plt.rcParams['axes.grid'] = True

## Tensor

### Import library

In [3]:
# Pytorch library
import torch

### Create tensors of various ranks

In [4]:
# Rank 0 tensor (scalar)
# Don't be forget to convert from dtype to float32. Numpy convert dtype to float64, and some Libraries doesn't work it. 
r0 = torch.tensor(1.0).float()

# Show type
print(type(r0))

# Show dtype
print(r0.dtype)

<class 'torch.Tensor'>
torch.float32


In [5]:
# Show shape
print(r0.shape)

# Show data
print(r0.data)

torch.Size([])
tensor(1.)


In [7]:
# Rank 1 tensor (vector)

# Create rank 1 NumPy variable
r1_np = np.array([1, 2, 3, 4, 5])
print(r1_np.shape)

# Convert from NumPy to tensor
r1 = torch.tensor(r1_np).float()

# Show dtype
print(r1.dtype)

# Show shape
print(r1.shape)

# Show data
print(r1.data)

(5,)
torch.float32
torch.Size([5])
tensor([1., 2., 3., 4., 5.])


In [8]:
# Rank 2 tensor (matrix)

# Create rank 2 Numpy variable
r2_np = np.array([[1, 5, 6], [4, 3, 2]])
print(r2_np.shape)

# Convert from NumPy to tensor
r2 = torch.tensor(r2_np).float()

# Show shape
print(r2.shape)

# Show data
print(r2.data)

(2, 3)
torch.Size([2, 3])
tensor([[1., 5., 6.],
        [4., 3., 2.]])


In [9]:
# Rank 3 tensor

# Initialize a random seed
torch.manual_seed(123)

# Create a normal distributed variable tensor with shape=[3, 2, 2]
# Function randn sets normal distributeed random numbers (average:0, variance:1) to elements
r3 = torch.randn((3, 2, 2))

# Show shape
print(r3.shape)

# Show data
print(r3.data)

torch.Size([3, 2, 2])
tensor([[[-0.1115,  0.1204],
         [-0.3696, -0.2404]],

        [[-1.1969,  0.2093],
         [-0.9724, -0.7550]],

        [[ 0.3239, -0.1085],
         [ 0.2103, -0.3908]]])


In [10]:
# Rank 4 tensor

# Create tensor with shape=[2, 3, 2, 2] and all elements of it are 1
# function ones sets 1.0 to all elements
r4 = torch.ones((2, 3, 2, 2))

# Show shape
print(r4.shape)

# Show data
print(r4.data)

torch.Size([2, 3, 2, 2])
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])


### Create tensor of integer

In [12]:
# r1 is a rank 1 tensor that has float32 data
# This tensor is converted torch.int64 by long function 
r5 = r1.long()

# Show dtype
print(r5.dtype)

# Show value
print(r5)

torch.int64
tensor([1, 2, 3, 4, 5])


### view function