## ライブラリのインポート

In [2]:
# ライブラリのインポート
import numpy as np

# Numpyの浮動小数点の表示精度
np.set_printoptions(suppress=True, precision=5)

## 定義

In [3]:
# array関数によるベクトル（1階配列）変数の定義
n1 = np.array([1, 2, 3, 4, 5, 6, 7])

# 結果確認
print(n1)

# 要素数確認
print(n1.shape)

# もう1つの方法
print(len(n1))

[1 2 3 4 5 6 7]
(7,)
7


In [6]:
# array関数により行列（2階配列）変数の定義
n2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

# 結果確認
print(n2)

# 要素数確認
print(n2.shape)

# もう1つの方法
print(len(n2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
4


In [7]:
# zeros関数ですべての要素=0のベクトルを定義
n3 = np.zeros(5)

# 結果確認
print(n3)

# 要素数確認
print(n3.shape)


[0. 0. 0. 0. 0.]
(5,)


In [8]:
# ones関数で全ての要素=1の行列を定義
n4 = np.ones((2, 3))

# 結果確認
print(n4)

# 要素数確認
print(n4.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [9]:
# 全ての要素が正規分布変数の3階配列
# 3行4列を2つ作る。乱数は平均0、分散1の正規分布関数で作られる。
n5 = np.random.randn(2, 3, 4)

# 結果確認
print(n5)

# 要素数確認
print(n5.shape)

[[[-0.69659  1.62451  0.02738 -0.30406]
  [-0.50303  1.84323 -0.21807 -0.01983]
  [-2.45935  1.07962 -1.31554 -0.92254]]

 [[ 0.93206 -1.78111  0.64711 -0.33888]
  [ 0.43662 -0.04861 -0.99886 -0.44065]
  [-0.75657  0.02427  0.69656 -0.32799]]]
(2, 3, 4)


In [10]:
# linspace関数によるグラフ描画用数値配列

# 等間隔に点を取る
# 第1引数：始点（最小値）
# 第2引数：終点（最大値）
# 3番目の引数がこの区間に作る点の数/(植木算)になる点に注意。区間を10等分する場合は11個とる必要がある
n6 = np.linspace(-1, 1, 11)

# 結果確認
print(n6)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


In [11]:
# arange関数によるグラフ描画用配列

# 等間隔に点を取る
# 第1引数：区間の始点（最小値）
# 第2引数：区間の終点 (第2引数は最大値だが、「この値未満」であることに注意)
# 第3引数：刻み幅
n7 = np.arange(-1, 1.2, 0.2)

# 結果確認
print(n7)

[-1.  -0.8 -0.6 -0.4 -0.2 -0.   0.2  0.4  0.6  0.8  1. ]



## 操作

In [13]:
# 特定行・列の抽出

# 元の変数
print(n2)

# すべての行の0列を抽出
# 行要素：カンマより前は行の範囲、後ろは列の範囲
# : は全ての要素を意味するので「全ての行の0列目」
n8 = n2[:, 0]
print(n8)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  4  7 10]


In [14]:
# 1行目と3行目を抽出
# True / False の要素の配列で指定する
# 指定の仕方は下記の通り行と同じ要素数を持つTrue/Falseを配置
#    [1, 2, 3],     False
#    [4, 5, 6],     True
#    [7, 8, 9],     False
#    [10, 11, 12]   True

n2_index = np.array([False, True, False, True])
n9 = n2[n2_index]
print(n9)

[[ 4  5  6]
 [10 11 12]]


In [15]:
# reshape関数のトレーニング

n10 = np.array(range(24))

#  結果確認
print(n10)

# 3x8の2階配列に変形
n11 = n10.reshape(3,8)

# 結果確認
print(n11)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [16]:
# -1を指定すると自動計算
# 2 * x * 4 = 24、x = 3
n12  = n10.reshape(2, -1, 4)

# 結果確認
print(n12.shape)

(2, 3, 4)


In [18]:
# N要素のベクトルn10を、1行N列に変形

# 元の変数（1階配列）
print(n10.shape)

# 変形
n13 = n10.reshape(1, -1)

#結果確認
print(n13.shape)

(24,)
(1, 24)
