## ライブラリのインポート

In [1]:
# ライブラリのインポート
import numpy as np

# Numpyの浮動小数点の表示精度
np.set_printoptions(suppress=True, precision=5)

## 定義

### array関数による定義

In [2]:
# array関数によるベクトル（1階配列）変数の定義
n1 = np.array([1, 2, 3, 4, 5, 6, 7])

# 結果確認
print(n1)

# 要素数確認
print(n1.shape)

# もう1つの方法
print(len(n1))

[1 2 3 4 5 6 7]
(7,)
7


In [3]:
# array関数により行列（2階配列）変数の定義
n2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

# 結果確認
print(n2)

# 要素数確認
print(n2.shape)

# もう1つの方法
print(len(n2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
4


### zeros関数、ones関数などの利用

In [4]:
# zeros関数ですべての要素=0のベクトルを定義
n3 = np.zeros(5)

# 結果確認
print(n3)

# 要素数確認
print(n3.shape)


[0. 0. 0. 0. 0.]
(5,)


In [5]:
# ones関数で全ての要素=1の行列を定義
n4 = np.ones((2, 3))

# 結果確認
print(n4)

# 要素数確認
print(n4.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [6]:
# 全ての要素が正規分布変数の3階配列
# 3行4列を2つ作る。乱数は平均0、分散1の正規分布関数で作られる。
n5 = np.random.randn(2, 3, 4)

# 結果確認
print(n5)

# 要素数確認
print(n5.shape)

[[[-0.38664  0.80003  0.42162  0.76233]
  [ 1.17992 -0.39983  2.06453 -0.19525]
  [-0.41219 -0.03447  0.14669  0.47719]]

 [[-1.42487 -0.48202  0.81981  0.28082]
  [ 1.42584  0.59189  0.11317  1.1589 ]
  [ 0.0098  -1.51753 -0.23079  0.65945]]]
(2, 3, 4)


### グラフ描画用の数値配列の生成

In [7]:
# linspace関数によるグラフ描画用数値配列

# 等間隔に点を取る
# 第1引数：始点（最小値）
# 第2引数：終点（最大値）
# 3番目の引数がこの区間に作る点の数/(植木算)になる点に注意。区間を10等分する場合は11個とる必要がある
n6 = np.linspace(-1, 1, 11)

# 結果確認
print(n6)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


In [8]:
# arange関数によるグラフ描画用配列

# 等間隔に点を取る
# 第1引数：区間の始点（最小値）
# 第2引数：区間の終点 (第2引数は最大値だが、「この値未満」であることに注意)
# 第3引数：刻み幅
n7 = np.arange(-1, 1.2, 0.2)

# 結果確認
print(n7)

[-1.  -0.8 -0.6 -0.4 -0.2 -0.   0.2  0.4  0.6  0.8  1. ]



## 操作

### 特定業・列の抽出

In [9]:
# 特定行・列の抽出

# 元の変数
print(n2)

# すべての行の0列を抽出
# 行要素：カンマより前は行の範囲、後ろは列の範囲
# : は全ての要素を意味するので「全ての行の0列目」
n8 = n2[:, 0]
print(n8)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  4  7 10]


In [10]:
# 1行目と3行目を抽出
# True / False の要素の配列で指定する
# 指定の仕方は下記の通り行と同じ要素数を持つTrue/Falseを配置
#    [1, 2, 3],     False
#    [4, 5, 6],     True
#    [7, 8, 9],     False
#    [10, 11, 12]   True

n2_index = np.array([False, True, False, True])
n9 = n2[n2_index]
print(n9)

[[ 4  5  6]
 [10 11 12]]


### reshape関数

In [11]:
# reshape関数のトレーニング

n10 = np.array(range(24))

#  結果確認
print(n10)

# n10を3x8の2階配列に変形
n11 = n10.reshape(3,8)

# 結果確認
print(n11)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [12]:
# -1を１箇所だけ設定可能
# -1を指定すると自動計算
# 2 * x * 4 = 24、x = 3
n12  = n10.reshape(2, -1, 4)

# 結果確認
print(n12.shape)

(2, 3, 4)


In [13]:
# N要素のベクトルn10を、1行N列に変形

# 元の変数（1階配列）
print(n10.shape)

# 変形
n13 = n10.reshape(1, -1)

#結果確認
print(n13.shape)

(24,)
(1, 24)


### 軸の入れ替え

In [14]:
# 転置行列
print(n2)

n14 = n2.T
print(n14)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [15]:
# 軸の順番を入れ替える

# 元の変数
print(n12.shape)
print(n12)

# 軸を(1, 2, 0)の順に入れ替える
n14 = np.transpose(n12, (1, 2, 0))

# 結果確認
print(n14.shape)
print(n14)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


### 行列の連結

In [16]:
# 操作元の配列

# 2行3列の行列
n16 = np.array(range(1, 7)).reshape(2, 3)
n17 = np.array(range(7, 13)).reshape(2, 3)

# 3要素のベクトル
n18 = np.array(range(14, 17))

# 2要素のベクトル
n19 = np.array(range(17, 19))

print(n16)
print(n17)
print(n18)
print(n19)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[14 15 16]
[17 18]


In [17]:
# 行列同士の縦連結
n20 = np.vstack([n16, n17])
print(n20)

# 行列とベクトル間の縦連結
n21 = np.vstack([n16, n18])
print(n21)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [14 15 16]]


In [18]:
# 行列同士の横連結
n22 = np.hstack([n16, n17])
print(n22)

# 行列とベクトル間の横連結
# ベクトルのshapeを(N, 1)形式にする
n23 = n19.reshape(-1, 1)
n24 = np.hstack([n16, n23])
print(n24)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3 17]
 [ 4  5  6 18]]


## 演算

### Numpy変数間の演算

In [19]:
# 演算元変数
print(n16)
print(n17)

# 業列間の演算
n25 = n16 + n17

# 結果の確認 
print(n25)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]


### ブロードキャスト機能

In [20]:
# ブロードキャスト機能

# 演算元変数
print(n1)

# 全ての要素から同じ値を引く
n22 = n1 - 4

# 結果確認
print(n22)

[1 2 3 4 5 6 7]
[-3 -2 -1  0  1  2  3]


### ユニバーサル機能

In [21]:
# xの配列の準備
# 区間[0, 2PI]を24等分
x = np.linspace(0, 2*np.pi, 25)

# y = sin(x)の計算
# ユニバーサル関数呼び出し
y = np.sin(x)
print(y)

[ 0.       0.25882  0.5      0.70711  0.86603  0.96593  1.       0.96593
  0.86603  0.70711  0.5      0.25882  0.      -0.25882 -0.5     -0.70711
 -0.86603 -0.96593 -1.      -0.96593 -0.86603 -0.70711 -0.5     -0.25882
 -0.     ]


### 集約関数

In [22]:
# 集約関数

print(f'元の変数: {n1}')

 # 和の計算 sum関数
n23 = np.sum(n1)
print(f'和: {n23}')

 # 平均の計算 mean関数
n24 = np.mean(n1)
print(f'平均: {n24}')

 # 最大の計算 max関数
n25 = np.max(n1)
print(f'最大値: {n25}')

# 最小の計算 min関数
# こういう書き方もできる
n26 = n1.min()
print(f'最小値: {n26}')

元の変数: [1 2 3 4 5 6 7]
和: 28
平均: 4.0
最大値: 7
最小値: 1


## 応用例

### 2つの変数の一致数から精度計算

In [23]:
# 2つの変数の一致数から精度計算
# 0か1かの予測するモデルに対して正解値と予測値の一致率（Accuracy）を計算する

# 2つのNumPy配列の準備
# 正解値

yt = np.array([1, 1, 0, 1, 0, 1, 1, 0, 1, 1])
yp = np.array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1])

# 内容表示
print(yt)
print(yp)

[1 1 0 1 0 1 1 0 1 1]
[1 1 0 1 0 1 1 1 1 1]


In [24]:
# 配列の各要素を同時に比較する
matched = (yt == yp)
print(matched)

[ True  True  True  True  True  True  True False  True  True]


In [25]:
# さらにこの結果にsum関数をかける
# 対象変数がブーリアン型の場合 True -> 1 False -> 0 に変換される

# 正解数がブーリアン型の場合
correct = matched.sum()

# 全体数はlen(matched)で計算可能
total = len(matched)

# 精度の計算
accuracy = correct / total

print(f'正解数: {correct} 全体数: {total} 精度: {accuracy: .3f}')

正解数: 9 全体数: 10 精度:  0.900


### ベクトルの数値を1次関数で変換して[0, 1]の範囲に収まるようにする

In [26]:
# ベクトルの数値を1次関数で変換して[0, 1]の範囲に収まるようにする
# 集約関数とブロードキャストの組み合わせ例

# 全ての値を[0, 1]の範囲に入るように変換する

# 元の変数
print(n1)

# 最大値と最小値を集約関数で取得
n1_max = n1.max()
n1_min = n1.min()
print(n1_max, n1_min)

[1 2 3 4 5 6 7]
7 1


In [27]:
# 変換（ブロードキャスト機能の利用）
# n27 = ([1 2 3 4 5 6 7] - 1) / (7 - 1)
# n1_minとn1_maxは定数なので、全体としてn1の1次間数になっている
n27 = (n1 - n1_min) / (n1_max - n1_min)
print(n27)

[0.      0.16667 0.33333 0.5     0.66667 0.83333 1.     ]


### ある条件を満たす行の抽出

In [28]:
# 「n2の0列が偶数」を判断

# 元の変数
print(n2)

# n2[:, 0]は特定行・列の抽出
# ブロードキャスト機能を利用
n28 = n2[:, 0] % 2 == 0 

# 結果確認
print(n28)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[False  True False  True]


In [29]:
# n28がTrueの行のみを抽出

print(n2)
n29 = n2[n28]

# 結果確認
print(n29)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [10 11 12]]
